stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "билд"
    - npm install
    - npm run build

test:
  stage: test
  script:
    - echo "тест"
    - npm test

deploy:
  stage: deploy
  script:
    - echo "деплой"
    - scp -r ./dist/* user@server:/var/www/html/
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
