FROM python:3.9-slim

COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app
RUN useradd -m appuser
USER appuser
CMD ["python3", "app.py"]